# Generated by Django 4.2.2 on 2023-06-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backstage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="director",
            name="award",
            field=models.ManyToManyField(
                related_name="director_awards", to="backstage.award"
            ),
        ),
    ]
