# Generated by Django 4.2.2 on 2023-06-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backstage", "0002_alter_director_award"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="award",
            field=models.ManyToManyField(
                related_name="actor_awards", to="backstage.award"
            ),
        ),
        migrations.AlterField(
            model_name="play",
            name="award",
            field=models.ManyToManyField(related_name="awards", to="backstage.award"),
        ),
    ]
