# Generated by Django 4.2.2 on 2023-06-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backstage", "0003_alter_actor_award_alter_play_award"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actor",
            options={"verbose_name": "actor", "verbose_name_plural": "actors"},
        ),
        migrations.RenameField(
            model_name="actor",
            old_name="award",
            new_name="awards",
        ),
        migrations.RenameField(
            model_name="director",
            old_name="award",
            new_name="awards",
        ),
        migrations.RenameField(
            model_name="play",
            old_name="award",
            new_name="awards",
        ),
        migrations.AddField(
            model_name="play",
            name="description",
            field=models.TextField(default="Best ever play"),
        ),
        migrations.AlterField(
            model_name="award",
            name="year",
            field=models.IntegerField(),
        ),
    ]
