# Generated by Django 4.2.2 on 2023-07-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backstage", "0017_alter_play_on_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="average_fee",
            field=models.PositiveIntegerField(),
        ),
    ]
