# Generated by Django 4.2.2 on 2023-08-26 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backstage", "0019_alter_actor_average_fee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=255)),
                ("date", models.DateField(auto_now_add=True)),
                ("text", models.TextField(default="Best ever play")),
                ("header", models.CharField(default="Best ever play", max_length=500)),
                ("author", models.CharField(max_length=200)),
                (
                    "play",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="reviews",
                        to="backstage.play",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
